version: '3.6'
services:

  test_redis:
    container_name: test-redis
    image: redis
    user: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    restart: always

networks:
  default:
    driver: bridge
