version: '3.6'
services:

  test:
    platform: linux/amd64
    container_name: test
    build:
      context: ./
      dockerfile: Dockerfile.test
      args:
        SSH_PRV_KEY: ${SSH_PRV_KEY}
    env_file:
      - ./.env.Test
    entrypoint:
      - sh
      - -c
      - "sh entrypoint.test.sh"
    volumes:
      - ./:/var/www/nest/redis-adapter
      - /var/www/nest/redis-adapter/node_modules
    depends_on:
      - test_redis
    tty: true

  test_redis:
    container_name: test-redis
    image: redis
    user: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    restart: always

networks:
  default:
    driver: bridge
